version: '3'

services:
    nginx:
        image: nginx:1.19
        ports:
            - 8082:80
        volumes:
            - ./web:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        command: ["sh", "-c", "chown www-data:www-data /usr/share/nginx/html/src/uploads && nginx -g 'daemon off;'"]
        depends_on:
            - php

    php:
        image: php:7.4-fpm
        volumes:
            - ./web:/usr/share/nginx/html

